# Generated by Django 6.0.1 on 2026-02-23 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customerfield_customertag_customer_anniversary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('default_reminder_minutes', models.IntegerField(default=30, help_text='Default reminder time before task due date', verbose_name='Default Reminder (minutes)')),
                ('auto_create_follow_up', models.BooleanField(default=False, help_text='Automatically create a follow-up task after completing a call or meeting', verbose_name='Auto-create Follow-up')),
                ('working_hours_start', models.TimeField(default='09:00', verbose_name='Working Hours Start')),
                ('working_hours_end', models.TimeField(default='18:00', verbose_name='Working Hours End')),
            ],
            options={
                'verbose_name': 'Task Settings',
                'verbose_name_plural': 'Task Settings',
                'db_table': 'tasks_settings',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('task_type', models.CharField(choices=[('task', 'Task'), ('call', 'Call'), ('meeting', 'Meeting'), ('email', 'Email'), ('follow_up', 'Follow-up')], db_index=True, default='task', max_length=20, verbose_name='Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Due Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('assigned_to', models.UUIDField(blank=True, db_index=True, help_text='UUID of the user assigned to this task', null=True, verbose_name='Assigned To')),
                ('related_lead', models.UUIDField(blank=True, help_text='UUID of a related lead or entity', null=True, verbose_name='Related Lead')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Duration for calls and meetings', null=True, verbose_name='Duration (minutes)')),
                ('result', models.TextField(blank=True, help_text='Outcome of call or meeting', verbose_name='Result')),
                ('location', models.CharField(blank=True, help_text='Location for meetings', max_length=255, verbose_name='Location')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Recurring')),
                ('recurrence_rule', models.JSONField(blank=True, help_text='JSON recurrence configuration', null=True, verbose_name='Recurrence Rule')),
                ('reminder_before_minutes', models.IntegerField(default=30, verbose_name='Reminder Before (minutes)')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'db_table': 'tasks_task',
                'ordering': ['-due_date', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['hub_id', 'status', 'due_date'], name='tasks_task_hub_id_c7b72d_idx'), models.Index(fields=['hub_id', 'task_type'], name='tasks_task_hub_id_c10440_idx'), models.Index(fields=['hub_id', 'assigned_to'], name='tasks_task_hub_id_052854_idx'), models.Index(fields=['hub_id', 'priority'], name='tasks_task_hub_id_ba183a_idx'), models.Index(fields=['hub_id', 'customer'], name='tasks_task_hub_id_29cc6a_idx')],
            },
        ),
    ]
